// Ver.7.0 Part1: 歌ネット掲載曲名とユーザー提供画像を基に整理した初期曲データ。
// 歌詞本文は含みません。既存曲と同じタイトルは一括登録時に自動でスキップされます。
export const initialSongs = [
  { title: "TO BE", reading: "とぅーびー", album: "DIGITAL SINGLE", releaseDate: "2026-04-15" },
  { title: "相思相愛 with SOIL&\"PIMP\"SESSIONS", album: "DIGITAL SINGLE", releaseDate: "2025-11-19" },
  { title: "ハートビート", album: "DIGITAL SINGLE", releaseDate: "2024-05-10" },
  { title: "旅人", album: "DIGITAL SINGLE", releaseDate: "2024-05-10" },
  { title: "青青青", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "YARE YARE", reading: "やれやれ", album: "青青青", releaseDate: "2023-12-06" },
  { title: "C&K XV", reading: "しーあんどけーふぃふてぃーん", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "自由に", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "スナック18番", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "挿入歌", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "DAN", reading: "だん", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "血出す見出す精出す", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "寝ている顔を見ている", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "believe", reading: "びりーぶ", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "メーデー", album: "CK PEAS", releaseDate: "2023-12-06" },
  { title: "C&K XIV", reading: "しーあんどけーふぉーてぃーん", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "GENTEN", reading: "げんてん", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "I.M.A", reading: "いーま", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "今君に伝えたいこと", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "HELLO SAY GOODBYE", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "足りないとこだらけの僕らだから", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "Brand New Days", reading: "ぶらんにゅーでいず", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "上を行くメイク", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "ガン見しとけ！ for DANCER", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "メリチキ", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "混浴", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "夜空", album: "CK OILY", releaseDate: "2022-11-16" },
  { title: "C&K XIII", reading: "しーあんどけーさーてぃーん", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "KARADANONAKADAKARADA", reading: "からだのなかだからだ", album: "CK TOKEN", releaseDate: "2021-08-18" },
  { title: "誘惑", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "テレカクシー", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "うたをうたお", album: "CK TOKEN", releaseDate: "2021-10-20" },
  { title: "ONE DAY", reading: "わんでい", album: "うたをうたお", releaseDate: "2021-10-20" },
  { title: "コドナ", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "Alma", reading: "あるま", album: "CK TOKEN / 御社のCMソング", releaseDate: "2020-11-04" },
  { title: "アサトヒカリ", album: "CK TOKEN", releaseDate: "2020-08-05" },
  { title: "あの日のスウィートメロディ", album: "CK TOKEN", releaseDate: "2021-04-07" },
  { title: "traveling carnival〜移動式遊園地のテーマ〜", album: "あの日のスウィートメロディ", releaseDate: "2021-04-07" },
  { title: "揮発油", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "しるし", album: "CK TOKEN", releaseDate: "2021-12-15" },
  { title: "嗚呼、麗しき人生", album: "CK TOKEN", releaseDate: "2019-08-07" },
  { title: "走りだせ", album: "嗚呼、麗しき人生", releaseDate: "2019-08-07" },
  { title: "C&K XI", reading: "しーあんどけーいれぶん", album: "嗚呼、麗しき人生", releaseDate: "2019-08-07" },
  { title: "年中Funky", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "Drive!!!", reading: "どらいぶ", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "TANSAN FLAVOR", reading: "たんさんふれーばー", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "Home", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "MAMANIE", reading: "ままにえ", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "エナジー補給戦隊スイハンジャー", album: "御社のCMソング", releaseDate: "2020-11-04" },
  { title: "Y", reading: "わい", album: "55", releaseDate: "2017-06-07" },
  { title: "ヒカリトカゲ", album: "55", releaseDate: "2017-06-07" },
  { title: "ダイヤモンド", album: "55", releaseDate: "2017-06-07" },
  { title: "ワタタリカ", album: "55", releaseDate: "2017-06-07" },
  { title: "道", album: "55", releaseDate: "2017-06-07" },
  { title: "交差点", album: "55", releaseDate: "2017-06-07" },
  { title: "追憶", album: "55", releaseDate: "2017-06-07" },
  { title: "ドラマ", album: "TEN", releaseDate: "2018-11-21" },
  { title: "クローバーとダイヤモンド", album: "TEN", releaseDate: "2018-11-21" },
  { title: "精鋭", album: "TEN", releaseDate: "2018-11-21" },
  { title: "入浴", album: "TEN", releaseDate: "2018-11-21" },
  { title: "帰れ", album: "TEN", releaseDate: "2018-11-21" },
  { title: "APAP", reading: "えーぴーえーぴー", album: "TEN", releaseDate: "2018-11-21" },
  { title: "※がある", album: "TEN", releaseDate: "2018-11-21" },
  { title: "幸せのディスタンス", album: "TEN", releaseDate: "2018-11-21" },
  { title: "愛を浴びて、僕がいる", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "みかんハート", album: "CK AND MORE...", releaseDate: "2013-10-30" },
  { title: "終わりなき輪舞曲", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "キミノ言葉デ", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "アイアイのうた〜僕とキミと僕等の日々〜", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "ジャパンパン〜日本全国地元化計画〜", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "踊LOCCA〜around the world 新たなる冒険〜", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "ジェニファー何度もあなたに恋をする", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "続→60億分の1", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "へべれけ宣言", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "Sun Son Sound feat.九州男", reading: "さんさんさうんどふぃーとくすお", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "MATSURI", reading: "まつり", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "パーティ☆キング", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "to di Bone", reading: "とぅーでぃぼーん", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "milky way", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "HOTEL NETTAI-YA", reading: "ほてるねったいや", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "梅雨明け宣言", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "JOY A LIFE", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "みんなのうた", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "DANCE☆MAN(WOKKY WOKKY×BOGGIE WOGGIE)", reading: "だんすまんうぉっきーうぉっきーぼぎーうぉぎー", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "EVERYBODY", reading: "えぶりばでぃ", album: "CK A-YANKA!!!", releaseDate: "2010-09-22" },
  { title: "歩きだせ", album: "CK A-YANKA!!!", releaseDate: "2010-09-22" },
  { title: "ぼくのとなりにいてくれませんか？", album: "CK A-YANKA!!!", releaseDate: "2010-09-22" },
  { title: "サヨナラ", album: "CK A-YANKA!!!", releaseDate: "2010-09-22" },
  { title: "ラブリーデイ", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "1日の向こう側", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "カモメ", album: "DIGITAL SINGLE", releaseDate: "2014-11-24" },
  { title: "空気", album: "One_day", releaseDate: "2020-12-23" },
  { title: "AND MORE...", reading: "あんどもあ", album: "CK AND MORE...", releaseDate: "2013-10-30" },
  { title: "両腕が翼ならば", album: "アイのうたたち2", releaseDate: "2021-02-26" },
  { title: "JIMOTO with カサリンチュ", reading: "じもとうぃずかさりんちゅ", album: "アイのうたたち2", releaseDate: "2021-02-26" },
  { title: "BYE BYE BOO", reading: "ばいばいぶー", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "にわとりのうた", album: "CK MUSIC", releaseDate: "2015-10-14" },
  { title: "GET@LADY", album: "CK JUNGLE!!!", releaseDate: "2013-02-06" },
  { title: "C&KΦ", reading: "しーあんどけーふぁい", album: "ライブ定番曲" },
  { title: "C&K XII", reading: "しーあんどけーとぅえるぶ", album: "KARADANONAKADAKARADA", releaseDate: "2021-08-18" },
  { title: "Listen", reading: "りっすん" },
  { title: "WARAEBA A-YO feat.オーサカ=モノレール", reading: "わらえばあーよふぃーとおーさかものれーる" },
  { title: "笑えや歌えや" },
  { title: "one way", reading: "わんうぇい" },
  { title: "ONCE MORE", reading: "わんすもあ" },
  { title: "MICHI with 九州男", reading: "みちうぃずくすお" },
  { title: "メモリーズ" },
  { title: "MENDOKUSE", reading: "めんどくせー" },
  { title: "YOU ARE MY FIRE〜お前にこの愛を捧ぐ〜", reading: "ゆーあーまいふぁいあーおまえにこのあいをささぐ" },
  { title: "hone made", reading: "ほーんめいど" },
  { title: "ぼくのお嫁になってくれませんか？" },
  { title: "僕の天使" },
  { title: "また逢う日まで" },
  { title: "パーティ☆キング(P××K×× remix) feat.九州男, TEE" },
  { title: "Piano", reading: "ぴあの" },
  { title: "HEY GIRL 〜腸活発女子〜", reading: "へいがーるちょうかっぱつじょし" },
  { title: "人間進化論" },
  { title: "NO MORE CRY", reading: "のーもあくらい" },
  { title: "8月28日" },
  { title: "ハナレ・バナレ" },
  { title: "春と君のシンフォニー" },
  { title: "天翔る少年" },
  { title: "電波マスター" },
  { title: "日曜の午後 〜for T&M〜" },
  { title: "日本ビート" },
  { title: "抱きしめたい" },
  { title: "Dalala", reading: "だらら" },
  { title: "DANCE WITH ME", reading: "だんすうぃずみー" },
  { title: "DANCE☆WOMAN", reading: "だんすうーまん" },
  { title: "DANCE HALL", reading: "だんすほーる" },
  { title: "上京がむしゃら物語" },
  { title: "四池さんのマーチ" },
  { title: "主役はU" },
  { title: "C&K", reading: "しーあんどけー" },
  { title: "C&K II", reading: "しーあんどけーつー" },
  { title: "C&K IV", reading: "しーあんどけーふぉー" },
  { title: "C&K V", reading: "しーあんどけーふぁいぶ" },
  { title: "C&K IX", reading: "しーあんどけーないん" },
  { title: "C&K X", reading: "しーあんどけーてん" },
  { title: "C&K3", reading: "しーあんどけーすりー" },
  { title: "CK目離ぃ〜娯乱島" },
  { title: "心の糸" },
  { title: "GORIN with RADIO FISH", reading: "ごりんうぃずらじおふぃっしゅ" },
  { title: "サンサン☆ブギー" },
  { title: "SUNSHINE", reading: "さんしゃいん" },
  { title: "カシオペア" },
  { title: "Good night Baby", reading: "ぐっどないとべいびー" },
  { title: "Good Luck", reading: "ぐっどらっく" },
  { title: "今を生きる" },
  { title: "winter tainer" },
  { title: "EVERYBODY (CK PEAS ver.)", reading: "えぶりばでぃしーけーぴーすばーじょん" },
  { title: "EVERYBODY(funcaster☆remix)", reading: "えぶりばでぃふぁんきゃすたーりみっくす" },
  { title: "ASE", reading: "あせ" },
  { title: "AM4:28 with KAKO", reading: "えーえむよじにじゅうはちうぃずかこ" },
  { title: "王様ゲーム" },
  { title: "雨のち晴れ" },
  { title: "Under the Moonlight", reading: "あんだーざむーんらいと" },
  { title: "言いたいのに言えない" },
  { title: "生きてるって、何だろう" },
  { title: "いたずらな罠" },
  { title: "愛の詩" },
  { title: "愛の戦士“アイダ”" },
  { title: "愛の光" },
  { title: "赤とんぼ" },
  { title: "スナック十八番" },
  { title: "SMILE×SMILE", reading: "すまいるすまいる" },
  { title: "タイムトラベル" },
];
